stages:
  - publish

sync-wireguard-apple:
  stage: publish
  only:
    refs:
      - /^release\/.*/
  before_script:
    - apt update && apt-get install -y connect-proxy
  script:
    - git clone "$CI_REPOSITORY_URL" --branch "$CI_COMMIT_BRANCH" _APP_CLONE;
    - cd _APP_CLONE
    - git remote add public git@github.com:ProtonVPN/wireguard-apple.git
    - git push public "$CI_COMMIT_BRANCH" -f

sync-go:
  stage: publish
  only:
    refs:
      - /^release\/.*/
  variables:
    OPENSOURCE_GO: "true"
  trigger:
    project: ProtonVPN/development/wireguard-go
    branch: release/ios
